-- Adds opaque Taskflow URL slots that pin a participant to one missing
-- counterbalance cell x speaker-pattern bundle. Raw URL tokens are never stored;
-- only SHA-256 hashes generated by scripts/generate_taskflow_gapfill.mjs are seeded.

ALTER TABLE sessions ADD COLUMN targeted_allocation_slot_id TEXT;
ALTER TABLE counterbalance_allocations ADD COLUMN targeted_allocation_slot_id TEXT;

CREATE TABLE IF NOT EXISTS targeted_allocation_slots (
  slot_id TEXT PRIMARY KEY,
  token_hash TEXT NOT NULL UNIQUE,
  allocation_cohort TEXT NOT NULL,
  allocation_strategy_version TEXT NOT NULL,
  cell_id INTEGER NOT NULL,
  speaker_pattern_bundle INTEGER NOT NULL CHECK(speaker_pattern_bundle BETWEEN 1 AND 10),
  status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open', 'claimed', 'completed')),
  claimed_session_id TEXT UNIQUE,
  claimed_at TEXT,
  completed_session_id TEXT,
  completed_at TEXT,
  claim_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY(cell_id) REFERENCES counterbalance_cells(cell_id)
);

CREATE INDEX IF NOT EXISTS idx_targeted_allocation_slots_scope
  ON targeted_allocation_slots(
    allocation_cohort, allocation_strategy_version, cell_id, speaker_pattern_bundle, status
  );
CREATE INDEX IF NOT EXISTS idx_targeted_allocation_slots_claim
  ON targeted_allocation_slots(status, claimed_session_id, updated_at);
